# generate_enums.py
"""Generate type-safe Enums + metadata sidecars from Riot static JSON."""
import re
import httpx
import keyword

from dataclasses import dataclass, field
from pathlib import Path
from typing import Callable

SOURCE_DIR = Path("./src/league")
if not SOURCE_DIR.exists():
    print("source directory not found")
    exit(1)

OUTPUT_DIR = SOURCE_DIR / "enums"
OUTPUT_DIR.mkdir(exist_ok=True)

@dataclass(frozen=True)
class EnumSpec:
    url: str  # static data endpoint
    class_name: str  # e.g. "Queue", "Map"
    id_field: str  # JSON key holding the numeric id
    name_field: str  # JSON key used to build the member name
    # Each meta field -> emitted as a sidecar dict. A field may be given as:
    #   "notes"                  -> const auto-named (redundant class prefix stripped)
    #   ("mapName", "NAME")      -> const explicitly named MAP_NAME
    meta_fields: tuple[str | tuple[str, str], ...] = ()
    # fallback when name_field is null/empty
    fallback: Callable[[dict], str] = field(
        default=lambda row: f"item_{row.get('id', 'x')}"
    )


def slug(text: str) -> str:
    """Turn arbitrary text into a valid UPPER_SNAKE identifier."""
    s = re.sub(r"\W+", "_", text).strip("_").upper()
    if not s:
        return ""
    if s[0].isdigit():
        s = f"Q_{s}"
    if keyword.iskeyword(s.lower()):
        s = f"{s}_"
    return s


def const_name(spec: EnumSpec, fld: str | tuple[str, str]) -> tuple[str, str]:
    """Resolve a meta field into (json_key, CONST_NAME).

    If an explicit name is given, it's used verbatim (prefixed by class name).
    Otherwise the field is UPPER_SNAKE'd and a redundant leading class-name
    fragment is stripped, so `mapName` on class `Map` -> MAP_NAME, not MAP_MAPNAME.
    """
    prefix = spec.class_name.upper()
    if isinstance(fld, tuple):
        key, suffix = fld
        return key, f"{prefix}_{suffix.upper()}"

    key = fld
    suffix = slug(re.sub(r"(?<!^)(?=[A-Z])", "_", fld))  # camelCase -> CAMEL_CASE
    # strip a redundant class-name fragment at the start (MAP_NAME from mapName)
    if suffix.startswith(prefix + "_"):
        suffix = suffix[len(prefix) + 1:]
    elif suffix == prefix:
        suffix = "VALUE"
    return key, f"{prefix}_{suffix}"


def build_rows(data: list[dict], spec: EnumSpec) -> list[dict]:
    seen_names: set[str] = set()
    seen_ids: set[int] = set()
    rows: list[dict] = []
    for entry in data:
        qid = entry.get(spec.id_field)
        if qid is None or qid in seen_ids:
            continue
        raw = entry.get(spec.name_field) or spec.fallback(entry)
        name = slug(str(raw)) or slug(spec.fallback(entry))
        base, i = name, 2
        while name in seen_names:
            name, i = f"{base}_{i}", i + 1
        seen_names.add(name)
        seen_ids.add(qid)
        rows.append({"name": name, "id": qid, "raw": entry})
    return rows


def render(spec: EnumSpec, rows: list[dict]) -> str:
    out = [
        '"""AUTO-GENERATED by generate_enums.py - do not edit."""\n',
        "from .enum_base import LookupEnum\n\n\n",
        f"class {spec.class_name}(LookupEnum):\n",
    ]
    if not rows:
        out.append("    pass\n")
    for r in rows:
        out.append(f"    {r['name']} = {r['id']}\n")

    for fld in spec.meta_fields:
        key, const = const_name(spec, fld)
        out.append(f"\n\n{const}: dict[{spec.class_name}, str | None] = {{\n")
        for r in rows:
            val = r["raw"].get(key)
            out.append(f"    {spec.class_name}.{r['name']}: {val!r},\n")
        out.append("}\n")

    return "".join(out)


def generate(spec: EnumSpec, out_dir: Path = OUTPUT_DIR) -> None:
    import httpx

    data = httpx.get(spec.url).json()
    rows = build_rows(data, spec)
    path = out_dir / f"{spec.class_name.lower()}s.py"
    path.write_text(render(spec, rows))
    print(f"wrote {path} ({len(rows)} members)")


SPECS = [
    EnumSpec(
        url="https://static.developer.riotgames.com/docs/lol/queues.json",
        class_name="Queue",
        id_field="queueId",
        name_field="description",
        meta_fields=(("description", "DESCRIPTION"), "map"),
    ),
    EnumSpec(
        url="https://static.developer.riotgames.com/docs/lol/maps.json",
        class_name="Map",
        id_field="mapId",
        name_field="mapName",
        meta_fields=("mapName", "notes"),  # -> MAP_NAME, MAP_NOTES
    ),
]


if __name__ == "__main__":
    for spec in SPECS:
        generate(spec)
