"""AUTO-GENERATED by generate_enums.py - do not edit."""

from .enum_base import LookupEnum


class Map(LookupEnum):
    SUMMONER_S_RIFT = 1
    SUMMONER_S_RIFT_2 = 2
    THE_PROVING_GROUNDS = 3
    TWISTED_TREELINE = 4
    THE_CRYSTAL_SCAR = 8
    TWISTED_TREELINE_2 = 10
    SUMMONER_S_RIFT_3 = 11
    HOWLING_ABYSS = 12
    BUTCHER_S_BRIDGE = 14
    COSMIC_RUINS = 16
    VALORAN_CITY_PARK = 18
    SUBSTRUCTURE_43 = 19
    CRASH_SITE = 20
    NEXUS_BLITZ = 21
    CONVERGENCE = 22
    RINGS_OF_WRATH = 30
    THE_BANDLEWOOD = 35


MAP_NAME: dict[Map, str | None] = {
    Map.SUMMONER_S_RIFT: "Summoner's Rift",
    Map.SUMMONER_S_RIFT_2: "Summoner's Rift",
    Map.THE_PROVING_GROUNDS: "The Proving Grounds",
    Map.TWISTED_TREELINE: "Twisted Treeline",
    Map.THE_CRYSTAL_SCAR: "The Crystal Scar",
    Map.TWISTED_TREELINE_2: "Twisted Treeline",
    Map.SUMMONER_S_RIFT_3: "Summoner's Rift",
    Map.HOWLING_ABYSS: "Howling Abyss",
    Map.BUTCHER_S_BRIDGE: "Butcher's Bridge",
    Map.COSMIC_RUINS: "Cosmic Ruins",
    Map.VALORAN_CITY_PARK: "Valoran City Park",
    Map.SUBSTRUCTURE_43: "Substructure 43",
    Map.CRASH_SITE: "Crash Site",
    Map.NEXUS_BLITZ: "Nexus Blitz",
    Map.CONVERGENCE: "Convergence",
    Map.RINGS_OF_WRATH: "Rings of Wrath",
    Map.THE_BANDLEWOOD: "The Bandlewood",
}


MAP_NOTES: dict[Map, str | None] = {
    Map.SUMMONER_S_RIFT: "Original Summer variant",
    Map.SUMMONER_S_RIFT_2: "Original Autumn variant",
    Map.THE_PROVING_GROUNDS: "Tutorial Map",
    Map.TWISTED_TREELINE: "Original Version",
    Map.THE_CRYSTAL_SCAR: "Dominion map",
    Map.TWISTED_TREELINE_2: "Last TT map",
    Map.SUMMONER_S_RIFT_3: "Current Version",
    Map.HOWLING_ABYSS: "ARAM map",
    Map.BUTCHER_S_BRIDGE: "Alternate ARAM map",
    Map.COSMIC_RUINS: "Dark Star: Singularity map",
    Map.VALORAN_CITY_PARK: "Star Guardian Invasion map",
    Map.SUBSTRUCTURE_43: "PROJECT: Hunters map",
    Map.CRASH_SITE: "Odyssey: Extraction map",
    Map.NEXUS_BLITZ: "Nexus Blitz map",
    Map.CONVERGENCE: "Teamfight Tactics map",
    Map.RINGS_OF_WRATH: "Arena map",
    Map.THE_BANDLEWOOD: "Map for Brawl (`BRAWL`). Work together with your team to escort minions into the enemy portal. No roles, no lanes, no pressure. Just a five-on-five brawl.",
}
